matrix:
  include:
    - { osx_image: xcode10.2, env: 'DST="platform=iOS Simulator,OS=12.2,name=iPhone 8"', os: osx, language: swift }

script:
- set -o pipefail &&
  xcodebuild 
  -enableCodeCoverage YES 
  -workspace KCCircularTimer.xcworkspace 
  -scheme Tests 
  -destination "$DST"
  ONLY_ACTIVE_ARCH=NO 
  test | xcpretty
- pod lib lint
