osx_image: xcode9.4
language: objective-c

script:
- set -o pipefail &&
  xcodebuild 
  -enableCodeCoverage YES 
  -workspace KCCircularTimer.xcworkspace 
  -scheme Tests 
  -sdk iphonesimulator11.4
  -destination "OS=11.4,name=iPhone 8"
  ONLY_ACTIVE_ARCH=NO 
  test | xcpretty
- pod lib lint
